import { Player } from "./leaderboard.interface";

export const players: Player[] = [
  {
    id: '4001',
    name: 'Samali Perera',
    img_url: 'https://th.bing.com/th/id/OIP.2KzBS2Bfpc7gVSPqPRCfGQHaJo?w=480&h=624&rs=1&pid=ImgDetMain',
    kite_height: '1600 M',
    rank: '1st',
    city: '@Matara',
  },
  {
    id: '4002',
    name: 'Amal Jay',
    img_url: 'https://th.bing.com/th/id/OIP.gO5LWYvoOMEzspq6dNRiTwAAAA?w=420&h=420&rs=1&pid=ImgDetMain',
    kite_height: '1500 M',
    rank: '2nd',
    city: '@Beliatta',
  },
  {
    id: '4003',
    name: 'Senurika',
    img_url: 'https://th.bing.com/th/id/OIP.9v3dZrOkWdDmpkVNodj5RAHaLG?w=667&h=1000&rs=1&pid=ImgDetMain',
    kite_height: '1400 M',
    rank: '3rd',
    city: '@Colombo',
  },
  {
    id: '4004',
    name: 'Kasun',
    img_url: 'assets/avatars/Avatar_Icons/avataaars (1).svg',
    kite_height: '1300M',
    rank: '4',
    city: '@weligama',
  },
  {
    id: '4005',
    name: 'Nipuna',
    img_url: 'assets/avatars/avataaars (2).svg',
    kite_height: '1200M',
    rank: '5',
    city: '@Matara',
  },
  {
    id: '4006',
    name: 'Ruwan ',
    img_url: `assets/avatars/avataaars (3).svg`,
    kite_height: '1100M',
    rank: '6',
    city: '@Galle',
  },
  {
    id: '4007',
    name: 'Nuwan',
    img_url: 'assets/avatars/avataaars (4).svg',
    kite_height: '1000M',
    rank: '7',
    city: '@Matara',
  },
  {
    id: '4008',
    name: 'Nuwan',
    img_url: 'https://th.bing.com/th/id/OIP.hd0I2qmDD3ZwQ18CnAQJaQHaHa?w=900&h=900&rs=1&pid=ImgDetMain',
    kite_height: '900M',
    rank: '8',
    city: '@Matara',
  },
  {
    id: '4009',
    name: 'Nuwan',
    img_url: 'https://th.bing.com/th/id/OIP.hd0I2qmDD3ZwQ18CnAQJaQHaHa?w=900&h=900&rs=1&pid=ImgDetMain',
    kite_height: '800M',
    rank: '9',
    city: '@Matara',
  },
  {
    id: '4010',
    name: 'Nuwan',
    img_url: 'https://th.bing.com/th/id/OIP.hd0I2qmDD3ZwQ18CnAQJaQHaHa?w=900&h=900&rs=1&pid=ImgDetMain',
    kite_height: '700M',
    rank: '10',
    city: '@Matara',
  },
];
